### PR TITLE
A lot of changes, mainly new README, and shift to EventEmitter.

### PR DESCRIPTION
**Pull request by AqilCont**

### CODE REVIEW

**Comment by AqilCont** [comment]
also this class was so broken it was completely unusable

**Comment by AqilCont** [comment]
*the `Stream`

**Comment by 117** [comment]
I've been wanting to redo the `Stream` class from the ground up. Skimmed a bit really like these changes! `EventEmitter` makes way more sense. Going to go over the files in detail and merge later tonight or tomorrow when i've got time.

**Comment by AqilCont** [comment]
Ok. Please remove all setTimeouts btw, they are complete crap to use when doing request based things. PLEASE use the request API itself to check for timeouts and other stuff but setTimeout is a complete no-no.

**Comment by AqilCont** [comment]
Ok, please review my changes. I fixed everything for the most part and it should be finished :D

**Comment by AqilCont** [comment]
I was also thinking to add a types property to the class so we can customize it a bit, and making the stream host restricted to BaseURL + a simpler way to add host.

**Comment by AqilCont** [comment]
Oh, i removed the message queueing... should i add it back?

**Comment by 117** [comment]
Taking a look now.

**Comment by 117** [comment]
I like your style, seeing a few ways of doing things I haven't seen elsewhere.

**Comment by AqilCont** [comment]
I really like clean code, even though it takes up more space >.<
Thanks!!!

**Comment by AqilCont** [comment]
Is there anything to fix?

**Comment by AqilCont** [comment]
~~i know i shouldn't discuss personal matters here but how was your trip?~~

**Comment by 117** [comment]
> ~i know i shouldn't discuss personal matters here but how was your trip?~

😆 crossed an entire state and the scenery is much better than where I was before. so i'd say well worth the drive

**Comment by 117** [comment]
Also running into an issue with the `Stream`, it seems to be authenticating before the connection is opened:
```typescript
// Sends an authentication request
this.connection.send({ // line 64
    action: 'authenticate',
    data: { key_id: client.options.key, secret_key: client.options.secret },
});
```
```typescript
throw new Error('WebSocket is not open: readyState 0 (CONNECTING)');
```
Perhaps move the authentication request inside the 'open' event?

**Comment by AqilCont** [comment]
OH RIGHT

**Comment by AqilCont** [comment]
I'm actually so dumb xddd

**Comment by 117** [comment]
> I'm actually so dumb xddd

Nah it's a simple fix lol. I've done way worse.

**Comment by AqilCont** [comment]
So should I add anything else? I could add the message queuing back ~~even though you really should just use the event~~

**Comment by 117** [comment]
> So should I add anything else? I could add the message queuing back ~even though you really should just use the event~

Message queueing was for if the client dc'd and was in the middle of reconnecting, the message wouldn't get lost. But that's on the client user now to deal with if they so wish.

Checking a few more things then i'll let you know.

**Comment by AqilCont** [comment]
Also, your trip sounded nice. I'm guessing you are finally taking your vacation after the pandemic thing toned down(still serious but at least the public is over it). xd

**Comment by AqilCont** [comment]
Oh ok. That's what i was referring to btw.

**Comment by 117** [comment]
One more thing, `JSON.stringify` before sending messages? Websocket doesn't like the object form apparently.

```typescript
this.connection.send(
    JSON.stringify({
        action: 'authenticate',
        data: { key_id: client.options.key, secret_key: client.options.secret },
    })
)
```

Without stringify-ing I get this:
```console
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
```

**Comment by AqilCont** [comment]
Oh yes please. I didn't do any tests yet as you can see, and it's showing.

**Comment by AqilCont** [comment]
Ok, done.

**Comment by 117** [comment]
Lol all good, our testing needs a revamp next. It's not very useful at the moment.

**Comment by AqilCont** [comment]
Yes xd

**Comment by AqilCont** [comment]
Can you merge and write the tests? I can't do this stuff well.

**Comment by 117** [comment]
It's technically a string now but is not valid JSON so no responses are being returned from the websocket server.

**Comment by 117** [comment]
Are you opposed to using `JSON.stringify()`?

**Comment by AqilCont** [comment]
OHHH right i forgot to add strings to property names. I keep being dumb. Also, I'm always opposed to writing unnecessary functions since I'm used to performance requirements made by my computer, and like to optimize where possible.

**Comment by AqilCont** [comment]
I took apart JSON.stringify once, and it's a bunch of unnecessary processing for small objects, since it's made to handle giant pieces of data.

**Comment by AqilCont** [comment]
I was actually frustrated about not taking out spaces before and you gave me an excuse to xd. ~~I'm still not satisfied since i left another one but ¯\_(ツ)_/¯~~

**Comment by 117** [comment]
The `object.toString()` method on the returned object doesn't tell us the error so perhaps `JSON.stringify()` should be used there?
```console
Error: There was an error in authorizing your websocket connection. Object received: [object Object]
```
The response object in this scenario looks like this when stringified:
```json
{"stream":"authorization","data":{"action":"authenticate","message":"access key verification failed","status":"unauthorized"}}
```

**Comment by AqilCont** [comment]
Hm, JSON.stringify should return the same output anyways.... why are you so obsessed with it xd?

**Comment by 117** [comment]
It is written in stream.ts as `object.ToString()` which prints [object Object] to console, not the object fields. :L

**Comment by AqilCont** [comment]
Yes, i fixed it.

**Comment by AqilCont** [comment]
Ahhh, I really should have tested it myself.......

**Comment by 117** [comment]
Works now.

**Comment by AqilCont** [comment]
Ok. Also, please find another issue as I missed my chance before.

**Comment by 117** [comment]
Let's just merge it and bump the version a full `0.1`? Work on it with some paper trade testing throughout the week.

**Comment by AqilCont** [comment]
Wait, just adding a few things.

**Comment by AqilCont** [comment]
Ok, done.

**Comment by AqilCont** [comment]
I think we should update the main client before the version update too... since it's also requires a major upgrade.

**Comment by AqilCont** [comment]
Also, I think this is production ready after this + client, so an upgrade to `1.0.0` would be more fitting

**Comment by 117** [comment]
I'm gonna merge what's here so far and bump the version by `0.1`, then we do client rework next and go straight to a release at `1.0.0`.

**Comment by AqilCont** [comment]
Yup :D

**Pull request merged**
