### PR TITLE
The rework of the Client class.

### PR DESCRIPTION
**Pull request by AqilCont**
The whole of the Client rework.

### CODE REVIEW

**Comment by AqilCont** [comment]
Also, even if we wanted to support the close method, the current way is the worst way imaginable. Ideally, we should put it in the `request` method, where it's actually most useful.

**Comment by AqilCont** [comment]
Also, Node automatically closes promises when exiting from what I know.

**Comment by AqilCont** [comment]
Yes it does: https://github.com/nodejs/node/issues/22088

**Comment by AqilCont** [comment]
So first thing to do now, is remove all of the promise allocation stuff.

**Comment by 117** [comment]
Perhaps we make a new ‘dev’ branch for this before beginning with changes? Then we can keep pushing changes without worry.

**Comment by AqilCont** [comment]
Oh, uhhhhh ok. I think I can switch, but I need to push my current changes first...

**Comment by AqilCont** [comment]
Ok, here is the start of the client rework I was talking about... I do feel as if it's a bit unnecessary but I love the fact that it can group together methods and make the coding experience a bit better.

**Comment by AqilCont** [comment]
Ok I have to go now, see you tomorrow. Also, some way to contact you would be nice(like a Discord or email)

**Comment by 117** [comment]
I switched the base branch to `dev` and merged the PR.

**Comment by 117** [comment]
> Ok I have to go now, see you tomorrow. Also, some way to contact you would be nice(like a Discord or email)

Discord `Bubbles#9497`

**Comment by AqilCont** [comment]
^ that started an awesome friendship

**Pull request merged**
